打印("1")
db = sqliteOpen(":memory:")
打印("2 open nil=")
打印(isNil(db))
打印("3 err=")
打印(sqliteErrMsg(db))
打印("4")
ok = sqliteExec(db, "CREATE TABLE t(x)")
打印("5 create=")
打印(ok)
打印("6")
ok = sqliteExec(db, "INSERT INTO t VALUES(1)")
打印("7 insert=")
打印(ok)
打印("8 lastId=")
打印(sqliteLastInsertId(db))
打印("9")
rows = sqliteQuery(db, "SELECT * FROM t")
打印("10 rows=")
打印(arrlen(rows))
打印("11 err3=")
打印(sqliteErrMsg(db))
打印("12")
sqliteClose(db)
打印("13 DONE")
