变量 arr = [10, 20, 30];
打印("len = ", len(arr));
push(arr, 40);
打印("push 40 = ", arr);
变量 v = pop(arr);
打印("pop = ", v, " arr = ", arr);
insert(arr, 1, 15);
打印("insert 15 at 1 = ", arr);
变量 r = remove(arr, 2);
打印("remove idx 2 = ", r, " arr = ", arr);
变量 sub = slice(arr, 1, 3);
打印("slice [1,3) = ", sub);
