打印("=== CRC32 ===")
打印(crc32(""))
打印(crc32("hello"))
打印(crc32("123456789"))
打印("=== MD5 ===")
打印(md5(""))
打印(md5("hello"))
打印(md5("a"))
打印(md5("The quick brown fox jumps over the lazy dog"))
打印("=== HMAC-MD5 ===")
打印(hmacMd5("Jefe", "what do ya want for nothing?"))
打印("=== SHA256 ===")
打印(sha256(""))
打印(sha256("hello"))
打印(sha256("abc"))
打印("=== HMAC-SHA256 ===")
打印(hmacSha256("key", "The quick brown fox"))
打印("CRYPTO_OK")
